export default {
  ALL_JOBS_SUCCESS: "ALL_JOBS_SUCCESS",
  ALL_JOBS_FAILURE: "ALL_JOBS_FAILURE",

  JOB_CANDIDATES_SUCCESS: "JOB_CANDIDATES_SUCCESS",
  JOB_CANDIDATES_FAILURE: "JOB_CANDIDATES_FAILURE",

  CLEAR_CANDIDATES: "CLEAR_CANDIDATES",

  CREATE_JOB_SUCCESS: "CREATE_JOB_SUCCESS",
  CREATE_JOB_FAILURE: "CREATE_JOB_FAILURE",
};
