export default {
  ALL_JOBS_SUCCESS: "ALL_JOBS_SUCCESS",
  ALL_JOBS_FAILURE: "ALL_JOBS_FAILURE",

  JOB_CANDIDATES_SUCCESS: "JOB_CANDIDATES_SUCCESS",
  JOB_CANDIDATES_FAILURE: "JOB_CANDIDATES_FAILURE",

  CLEAR_CANDIDATES: "CLEAR_CANDIDATES",
};
